### PR TITLE
Fix splash screen still showing when `false`

### PR DESCRIPTION
**Pull request by illusionyy**
Settings must be loaded before check

### CODE REVIEW

**Review by bucanero — APPROVED** [review]

**Comment by bucanero** [comment]
I'm wondering if the boot logo should be skipped or not, as I don't see as a terrible thing to let the user wait a few seconds for that animation.

Anyways, if we get a nice custom logo for the "GoldHen Dev team" in the future then we re-discuss this.

**Comment by illusionyy** [comment]
fow what i wanted, rapidly testing new code is slower due to having to wait for the animations, so i made these fixes.

**Comment by bucanero** [comment]
> fow what i wanted, rapidly testing new code is slower due to having to wait for the animations, so i made these fixes.

in that case, it could be a compilation flag like

```c
#ifndef DEBUG_ENABLE_LOG
    drawLogo(1);
#endif
```

then when you're building test builds, you just use the `DEBUG` flag and the logo and animations will be removed. (but only for debug builds, and not from user settings)

**Comment by illusionyy** [comment]
Yes that works as I compile debug build usually

**Comment by illusionyy** [comment]
Fixed in #95

**Pull request merged**
