### PR TITLE
Self updater

### PR DESCRIPTION
**Pull request by illusionyy**
- Downloads data zip and extracts to `/data/GoldHEN/goldcheats_data/`
- Moved assets path to `/data/GoldHEN/goldcheats_data/assets`
- Launches `goldcheats.elf` after extraction

### CODE REVIEW

**Comment by illusionyy** [comment]
Will rewrite using bgft

**Comment by LightningMods** [comment]
I believe this would be a better option and only requires an extra library
https://github.com/LightningMods/store-api

I have already tested and implemented it into Apollo
https://github.com/bucanero/apollo-ps4/pull/93

**Comment by bucanero** [comment]
another option/hack , based on latest Goldhen 2.3 would be to check if `/data/pkg` folder exists, then download the update there. I know it won't auto-install but it's a good fallback option.

Users that want to use plugins already have goldhen 2.3, so most cheat manager users should be able to rely on /data/pkg

**Comment by LightningMods** [comment]
@bucanero That does sound like a good fallback option so if they dont want to install the store or if there is an error (launch store function returns false) then you can just download the pkg to /data/pkg

**Comment by illusionyy** [comment]
Opened #81

**Comment by illusionyy** [comment]
I'll rethink the solution to the problem sometime. In the meantime will implement store api version.

My idea for bgft was to install dummy app that uninstalls the current app and installs new version from downloaded pkg. Though I may use a system level daemon for last resort.

**Comment by LightningMods** [comment]
> My idea for bgft was to install dummy app that uninstalls the current app and installs new version from downloaded pkg

you just explained the Store API, the Store in this case is the dummy app, also a daemon is overkill that's why I made the Store API so people wouldn't have to resort to that

**Comment by illusionyy** [comment]
Will PR store api version.

**Pull request closed without merging**
