### PR TITLE
Always set directory permission to `0777`

### PR DESCRIPTION
**Pull request by illusionyy**

### CODE REVIEW

**Review by bucanero — APPROVED** [review]

**Comment by bucanero** [comment]
did you check or test if this actually brings any issues? I'm still not sure if it's needed, as we didn't get any proper way to reproduce the original problem with the `patches` folder.

**Comment by illusionyy** [comment]
Yes I did test this change, no side effects so far. One theory that somehow the user created the folder with read only perms `0555` and app can't write to it. This fixes the issue by always setting permission to `0777` whenever we create a folders even if it already existed.

**Comment by illusionyy** [comment]
Making draft until reproducible steps are provided

**Comment by illusionyy** [comment]
Not an issue.

**Pull request closed without merging**
