### PR TITLE
Always set path permissions during download

### PR DESCRIPTION
**Pull request by illusionyy**
Can't reproduce but will leave it open for anyone who has the download issue can try this build.

### CODE REVIEW

**Comment by bucanero** [comment]
I think this is not needed as I still suspect that the problem is elsewhere and probably outside the cheat manager:
- Unzipping cheats never had an issue, even on users that couldn't open patches
- even if you chmod `/data/GoldHEN/patches`, inner folders like `json/` or `settings/` could have improper permissions, and the problem will still be the same
- Even during first run after app install the Cheat manager couldn't unpack the patches. (Another hint that the folder was already created beforehand)

I still suspect that some other tool or plugin has created the `patches` folder before Cheat Manager and didn't set the proper permissions.

Let's leave this as draft in case someone with the issue wants to try it.

**Comment by illusionyy** [comment]
If anything were to create the folders is my plugin, even then it was created with `0777`, no idea what's going on when the bug occurs.

**Comment by bucanero** [comment]
> If anything were to create the folders is my plugin, even then it was created with `0777`, no idea what's going on when the bug occurs.

do you know if the plugin loader also tries to create the folders?

also, is it needed for the plugins to create any folders? I think that they could just try to open or read the files, if they can't find anything then just skip the whole process, without creating any files or folders.

Right now the "enable/disable" settings are being managed by the homebrew app, so I think that plugins could only try to read files, and nothing else.

another thing to check, maybe the GoldHen payload also creates the folder? (need to ask Sistro)

**Comment by illusionyy** [comment]
GoldHEN does create `/data/GoldHEN` and `/cheats` folder but no idea what
permission (probably `0777`). Plugin loader only creates `/plugins` in
GoldHEN folder. Only problem would be that I create the folders every time
the plugin loads even if the folders already exist. Could that be the
problem?

**Comment by illusionyy** [comment]
> also, is it needed for the plugins to create any folders? I think that they could just try to open or read the files, if they can't find anything then just skip the whole process, without creating any files or folders.

The plugin creates folders first in order to make and load the settings files.

**Pull request closed without merging**
