### PR TITLE
Update pkg path to `/data/pkg`

### PR DESCRIPTION
**Pull request by illusionyy**

### CODE REVIEW

**Comment by bucanero** [comment]
Unless I'm missing something, I think this change is not needed:

I've been using `/data/` because that's the supported folder by [Internal PKG Installer](https://github.com/0x199/ps4-ipi) (IPI) by 0x199 , so by downloading to /data/ the user can install with IPI right away. I assume they can also use other tools like  ps4 xplorer too.

By using /data/pkg we break support for IPI and it doesn't make much sense.

**Comment by illusionyy** [comment]
Yes you're right, was thinking of changing it to /pkg to better fit the new goldhen internal HDD package install.

**Comment by bucanero** [comment]
> Yes you're right, was thinking of changing it to /pkg to better fit the new goldhen internal HDD package install.

oh, I forgot about that upcoming feature. Also LightningMods has been working on the Store API, so the update could be forwarded/handled by the Homebrew Store. I have a PR on Apollo to include the store api integration.

I think we need to discuss with the team and se what we want to do. Some open questions:
- do we want to use the Store API from LM?
- do we want to keep support for IPI app? (keep `/data`)
- do we want to go with `/data/pkg` and push users to have the latest goldhen payload?

Also, I'm not sure how many users actually use IPI, or if they use other tools like ps4 xplorer.
I know the ideal solution would be for Cheat Manager to auto-install the new .pkg, but I know that it's tricky to achieve such thing (it might be impossible?) and I never spent much time doing research for it. Perhaps you want to dig on a solution for this?

**Comment by illusionyy** [comment]
I do have one idea in mind that is to send a notification to the system that an application update is available, point it to locally downloaded pkg file and have it install that when user accepts it. This way we can keep the app fully portable and not have to rely on other things.

**Comment by bucanero** [comment]
> I do have one idea in mind that is to send a notification to the system that an application update is available, point it to locally downloaded pkg file and have it install that when user accepts it. This way we can keep the app fully portable and not have to rely on other things.

Oh, that sounds really cool! If it's possible that would be a neat, clean solution for sure.
I'm far from an expert on ps4 notifications so please feel free to do all the tests/changes you think are needed and if it works we'll use this new update method.

**Pull request closed without merging**
